# Generated by Django 5.2.5 on 2025-08-29 03:07

import django.db.models.deletion
import mi_app.models
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Clave de API')),
                ('activa', models.BooleanField(default=True, help_text='Desmarca esta casilla para desactivar la clave temporalmente.')),
                ('notas', models.TextField(blank=True, help_text="Notas internas (ej: 'Clave de cuenta personal', 'Clave de prueba').")),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clave de API de Gemini',
                'verbose_name_plural': 'Claves de API de Gemini',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionRuleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=False, help_text='Marca esta casilla para mostrar la ruleta en la web.')),
                ('titulo', models.CharField(default='¡Gira y Gana!', help_text="El título que aparecerá en el pop-up de la ruleta (ej: 'Especial de Halloween').", max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración de la Ruleta',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Fantasía Íntima', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('whatsapp_link', models.URLField(default='https://wa.me/51932187068')),
                ('facebook_link', models.URLField(default='https://web.facebook.com/fantasiaintimaa/')),
                ('instagram_link', models.URLField(default='https://www.instagram.com/fantasia_intima_lenceria')),
                ('tiktok_link', models.URLField(default='https://www.tiktok.com/@fantasa.ntima')),
                ('numero_yape_plin', models.CharField(default='987 654 321', max_length=15)),
                ('color_primario', models.CharField(default='#f9a8d4', help_text='Color principal (rosa claro)', max_length=7)),
                ('color_secundario', models.CharField(default='#f472b6', help_text='Color secundario (rosa medio)', max_length=7)),
                ('color_acento', models.CharField(default='#ec4899', help_text='Color de acento para botones (rosa fuerte)', max_length=7)),
                ('color_marron', models.CharField(default='#5C2C0C', help_text='Color marrón para títulos', max_length=7)),
                ('color_texto', models.CharField(default='#4b4244', help_text='Color del texto general', max_length=7)),
                ('fuente_principal_url', models.URLField(default='https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap', max_length=500)),
                ('fuente_principal_nombre', models.CharField(default="'Inter', sans-serif", max_length=100)),
                ('fuente_marca_url', models.URLField(default='https://fonts.googleapis.com/css2?family=Parisienne&display=swap', max_length=500)),
                ('fuente_marca_nombre', models.CharField(default="'Parisienne', cursive", max_length=100)),
                ('resetear_estilos', models.BooleanField(default=False, help_text='MARCA ESTA CASILLA Y GUARDA para restaurar todos los colores y fuentes a sus valores originales.')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="La URL de la página (ej: 'nosotros', 'politicas-de-envio')", max_length=200, unique=True)),
                ('contenido', models.TextField(help_text='Escribe aquí todo el contenido de la página. Puedes usar HTML si lo necesitas.')),
                ('publicada', models.BooleanField(default=True, help_text='Desmarca esta casilla para ocultar la página temporalmente.')),
            ],
            options={
                'verbose_name': 'Página Informativa',
                'verbose_name_plural': 'Páginas Informativas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TiradaRuleta',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ultima_tirada', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Tirada de Ruleta',
                'verbose_name_plural': 'Tiradas de Ruleta',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente.', max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('categorias_relacionadas', models.ManyToManyField(blank=True, help_text='Selecciona otras categorías para mostrar sus productos como relacionados.', to='mi_app.categoria', verbose_name='Categorías Relacionadas (para cross-selling)')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mi_app.categoria', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='PedidoWhatsApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_pedido', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('dni_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=255, null=True)),
                ('celular_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('ciudad_envio', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('variante_color', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.CharField(max_length=255)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mi_app.pedidowhatsapp')),
            ],
        ),
        migrations.CreateModel(
            name='PremioRuleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Texto que aparecerá en la ruleta (ej: '10% OFF', 'Envío Gratis'). Mantenlo corto.", max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Desmarca para quitar este premio de la ruleta.')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='mi_app.configuracionruleta')),
            ],
            options={
                'verbose_name': 'Premio de la Ruleta',
                'verbose_name_plural': 'Premios de la Ruleta',
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=mi_app.models.generar_codigo_cupon, max_length=15, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False, help_text='Marca esta casilla cuando el cliente haya canjeado el cupón por WhatsApp.')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to=settings.AUTH_USER_MODEL)),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.premioruleta')),
            ],
            options={
                'verbose_name': 'Cupón Generado',
                'verbose_name_plural': 'Cupones Generados',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio original del producto.', max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional: Si este precio está fijado, se mostrará como una oferta (con el precio original tachado).', max_digits=10, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('es_nueva_coleccion', models.BooleanField(default=False, verbose_name='¿Es de la Nueva Colección?')),
                ('categoria', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='mi_app.categoria', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='ColorVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código único (SKU) para esta variante específica (ej: DIS-COL-001-ROJO).', max_length=50, null=True, unique=True)),
                ('color', models.CharField(default='#FFFFFF', help_text='Haz clic para seleccionar un color exacto.', max_length=7)),
                ('imagen', models.ImageField(upload_to='productos/variantes/')),
                ('stock', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='mi_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: ¡Ofertas de Fin de Semana!', max_length=100)),
                ('subtitulo', models.CharField(blank=True, help_text='Ej: Hasta 50% en productos seleccionados', max_length=200)),
                ('imagen', models.ImageField(help_text='Imagen de fondo (1200x400px recomendado)', upload_to='banners/')),
                ('enlace', models.URLField(blank=True, help_text='URL a la que dirigirá el botón si NO hay productos destacados.')),
                ('texto_boton', models.CharField(default='Ver ahora', max_length=50)),
                ('activo', models.BooleanField(default=False, help_text='Marca esta casilla para que este banner se muestre en la página principal.')),
                ('productos_destacados', models.ManyToManyField(blank=True, related_name='banners', to='mi_app.producto')),
            ],
            options={
                'verbose_name': 'Banner Promocional',
                'verbose_name_plural': 'Banners Promocionales',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Ej: Casa, Oficina, Casa de mi tía', max_length=50)),
                ('destinatario', models.CharField(max_length=100, verbose_name='Nombre del destinatario')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección (Calle, número, etc.)')),
                ('referencia', models.CharField(blank=True, max_length=255, verbose_name='Referencia (Opcional)')),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('predeterminada', models.BooleanField(default=False, verbose_name='¿Es dirección predeterminada?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'unique_together': {('user', 'alias')},
            },
        ),
    ]
