# Generated by Django 5.2.5 on 2025-08-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionruleta',
            name='sonido_giro',
            field=models.FileField(blank=True, help_text='Sonido (MP3) que se reproduce mientras la ruleta gira.', null=True, upload_to='sonidos_ruleta/'),
        ),
        migrations.AddField(
            model_name='configuracionruleta',
            name='sonido_premio',
            field=models.FileField(blank=True, help_text='Sonido (MP3) que se reproduce al ganar un premio.', null=True, upload_to='sonidos_ruleta/'),
        ),
    ]
