# Generated by Django 5.2.5 on 2025-08-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_configuracionchatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_plin',
            field=models.ImageField(blank=True, help_text='Logo de Plin que se mostrará en el checkout.', null=True, upload_to='configuracion/pagos/'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_yape',
            field=models.ImageField(blank=True, help_text='Logo de Yape que se mostrará en el checkout.', null=True, upload_to='configuracion/pagos/'),
        ),
    ]
