# Generated by Django 5.2.5 on 2025-09-01 06:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_configuracionsitio_imagen_plin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionruleta',
            name='sonido_giro',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sonido (MP3) que se reproduce mientras la ruleta gira.', max_length=255, null=True, verbose_name='sonido_giro'),
        ),
        migrations.AlterField(
            model_name='configuracionruleta',
            name='sonido_premio',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sonido (MP3) que se reproduce al ganar un premio.', max_length=255, null=True, verbose_name='sonido_premio'),
        ),
    ]
