# Generated by Django 5.2.5 on 2025-08-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_nueva_coleccion',
            field=models.BooleanField(default=False, verbose_name='¿Es de la Nueva Colección?'),
        ),
    ]
