# Generated by Django 5.2.5 on 2025-09-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_alter_configuracionruleta_sonido_giro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariante',
            name='imagen_textura',
            field=models.ImageField(blank=True, help_text='Opcional: Sube aquí una imagen pequeña (ej: 50x50px) del estampado o textura si el color es complejo.', null=True, upload_to='productos/texturas/'),
        ),
    ]
