# Generated by Django 5.2.5 on 2025-09-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_colorvariante_imagen_textura'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Opcional: fecha/hora de fin para mostrar el banner', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Opcional: fecha/hora de inicio para mostrar el banner', null=True),
        ),
    ]
