# Generated by Django 5.2.5 on 2025-09-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0010_banner_modo_destino_banner_producto_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='usar_descuentos',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='banner',
            name='usar_nueva_coleccion',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
