# Generated by Django 5.2.5 on 2025-09-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0013_remove_banner_productos_destacados_remove_producto_en_grupo_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='enlace',
            field=models.URLField(blank=True, help_text="URL a la que dirigirá el botón si el modo es 'Enlace'."),
        ),
    ]
