# Generated by Django 5.2.5 on 2025-09-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0015_merge_0014_alter_banner_enlace_0014_banner_productos_destacados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='producto_destino',
            field=models.ForeignKey(blank=True, help_text='(Obsoleto si usas múltiples) Producto único rápido. Si además seleccionas varios abajo, se ignorará este campo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners_destino', to='mi_app.producto'),
        ),
    ]
