# Generated by Django 5.2.5 on 2025-09-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0015_merge_0014_alter_banner_enlace_0014_banner_productos_destacados'),
    ]

    # Esta migración se ha neutralizado porque el campo 'producto_destino' fue eliminado
    # por la otra rama (0016_remove_banner_producto_destino). Dejamos operaciones vacías
    # para que no falle en despliegues donde el orden de aplicación invierta remove/alter.
    operations = []
