# Generated by Django 5.2.5 on 2025-09-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0017_merge_0016_alter_banner_producto_destino_0016_remove_banner_producto_destino'),
    ]

    # Esta migración queda vacía porque el campo 'producto_destino' ya fue
    # eliminado en 0016_remove_banner_producto_destino.
    operations = []
