# Generated by Django 5.2.5 on 2025-09-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0011_producto_es_oferta'),
        ('mi_app', '0019_fix_banner_producto_destino_state'),
    ]

    operations = [
    ]
