# Generated by Django 5.2.5 on 2025-09-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0020_merge_20250903_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiradaruleta',
            name='attempts',
            field=models.PositiveIntegerField(default=1, help_text='Número total de intentos realizados (límite 3).'),
        ),
    ]
