# Generated by Django 5.2.5 on 2025-09-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0022_alter_tiradaruleta_attempts_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionruleta',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Fin de la promoción de la ruleta (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='configuracionruleta',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Inicio de la promoción de la ruleta (opcional)', null=True),
        ),
    ]
