# Generated by Django 5.2.5 on 2025-09-05 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0023_configuracionruleta_fecha_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='mi_app.colorvariante')),
            ],
        ),
    ]
