# Generated by Django 5.2.5 on 2025-09-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0026_add_normalized_search_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='promo_cooldown_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Cada cuántos segundos aparece un popup de promoción mientras el usuario navega.', verbose_name='Intervalo entre popups (segundos)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='show_promo_new_collection',
            field=models.BooleanField(default=True, help_text="Activa los popups de productos marcados como 'Nueva Colección'.", verbose_name="Mostrar 'Nueva Colección'"),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='show_promo_offers',
            field=models.BooleanField(default=True, help_text='Activa los popups de productos en oferta.', verbose_name="Mostrar 'Ofertas'"),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='show_promo_whatsapp',
            field=models.BooleanField(default=True, help_text='Activa el popup/pastilla para escribir por WhatsApp.', verbose_name='Mostrar WhatsApp'),
        ),
    ]
