# Generated by Django 5.2.5 on 2025-09-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0027_configuracionsitio_promo_cooldown_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='whatsapp_message_prefix',
            field=models.CharField(default='¡Hola {store_name}! ✨', help_text='Prefijo del mensaje. Puedes usar {store_name} para el nombre de la tienda.', max_length=120),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='whatsapp_message_template',
            field=models.TextField(default='{prefix}\n\nHe generado un pedido desde la web.\n\n*📋 Código de Pedido:* {order_code}\n*🔗 Ver Resumen Seguro:* {order_url}\n\n-----------------------------------\n*Resumen para referencia:*\n\n{items}*Total del Pedido: {total}*\n🚚 _(Este total no incluye el costo de envío)_\n\n¡Quedo a la espera de su confirmación para coordinar el pago y envío! 😊', help_text='Plantilla del mensaje. Variables disponibles: {prefix}, {store_name}, {order_code}, {order_url}, {items}, {total}.'),
        ),
    ]
