# Generated by Django 5.2.5 on 2025-10-05 04:02

from django.db import migrations, models


def copy_legacy_numbers(apps, schema_editor):
    ConfiguracionSitio = apps.get_model('mi_app', 'ConfiguracionSitio')
    try:
        cfg = ConfiguracionSitio.objects.get()
    except ConfiguracionSitio.DoesNotExist:
        return
    changed = False
    legacy = (cfg.numero_yape_plin or '').strip()
    if legacy:
        if not cfg.numero_yape:
            cfg.numero_yape = legacy
            changed = True
        if not cfg.numero_plin:
            cfg.numero_plin = legacy
            changed = True
    if changed:
        cfg.save(update_fields=['numero_yape','numero_plin'])


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0036_update_old_roulette_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='numero_plin',
            field=models.CharField(blank=True, default='', help_text='Número exclusivo para pagos vía Plin.', max_length=15),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='numero_yape',
            field=models.CharField(blank=True, default='', help_text='Número exclusivo para pagos vía Yape.', max_length=15),
        ),
        migrations.RunPython(code=copy_legacy_numbers, reverse_code=migrations.RunPython.noop)
    ]
